#*** Automatic generated file ***
#*** Don't touch!             ***
#Wed Apr 08 18:30:07 CEST 2026
build.date=08.04.2026 18\:30\:07
build.name=ChartJS Vaadin Wrapper
build.number=39
build.version=1.2
build.versionstring=ChartJS Vaadin Wrapper 1.2
