package com.byteowls.vaadin.chartjs.v3.options.scale;

import com.byteowls.vaadin.chartjs.v3.utils.JUtils;

import elemental.json.JsonObject;

/**
 * The linear scale is use to chart numerical data. It can be placed on either the x or y axis.
 * The scatter chart type automatically configures a line chart to use one of these scales for the x axis.
 * As the name suggests, linear interpolation is used to determine where a value lies on the axis.
 *
 * @author michael@byteowls.com
 */
public class LinearScale extends BaseScale<LinearScale> {

    private static final long serialVersionUID = 1723253099555272809L;

    private LinearTicks<LinearScale> linearTicks;
    
    private String grace;

    public LinearScale() {
        type("linear");
    }

    /**
     * It defines options for the tick marks that are generated by the axis.
     */
    @Override
    public LinearTicks<LinearScale> ticks() {
        if (this.linearTicks == null) {
            this.linearTicks = new LinearTicks<>(getThis());
        }
        return this.linearTicks;
    }
    
    public LinearScale grace(String grace) {
        this.grace = grace;
        return this;
    }

    @Override
    public LinearScale getThis() {
        return this;
    }

    @Override
    public JsonObject buildJson() {
        JsonObject map = super.buildJson();
        JUtils.putNotNull(map, "ticks", linearTicks);
        JUtils.putNotNull(map, "grace", grace);
        return map;
    }
}
